version: "3.4"

# Development environment override
services:
  php:
    volumes:
      - ./api:/srv/api:rw,cached
      - ./api/docker/php/conf.d/api-platform.dev.ini:/usr/local/etc/php/conf.d/api-platform.ini
      # if you develop on Linux, you may use a bind-mounted host directory instead
      # - ./api/var:/srv/api/var:rw
#      - ./docker/php/docker-entrypoint.sh:/usr/local/bin/docker-entrypoint:rw,cached
    environment:
      APP_ENV: dev

  front:
#    build:
#      context: ./front/docker
#      target: cat_game_fe_dev
    image: alexsuch/angular-cli:latest
    volumes:
      - ./front:/app:rw,cached
    working_dir: /app
#    entrypoint: ["npm", "i"]
    entrypoint: ["ng", "serve", "--port", "4200", "--host", "0.0.0.0"]
    ports:
      - "4200:4200"

  caddy:
    volumes:
      - ./api/docker/caddy/Caddyfile:/etc/caddy/Caddyfile:ro
      - ./api/public:/srv/api/public:ro
      - ./front/dist/front:/srv/front:ro

###> doctrine/doctrine-bundle ###
  database:
    ports:
      - target: 5432
        published: 5432
        protocol: tcp
###< doctrine/doctrine-bundle ###
