version: "3.4"

# Production environment override
services:
  php:
    environment:
      APP_ENV: prod
      APP_SECRET: ${APP_SECRET}

  database:
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
  
  cache:
    environment:
      AUTO_HTTPS: "disable_redirects"
