# see https://www.gnu.org/software/make/ for details
# cp this file to <project-root>/makefile
# cd <project-root>
# make

# Use .env file to overwrite parameters
include .env

SANDBOX_ROOT_DIR=/app

.PHONY: help sandbox build

up: only-on-laptop
	rsync --delete -avz -e "ssh -l ${SANDBOX_USER} -i dev/GCP_KEY_FILE -p 22 -o StrictHostKeyChecking=No -o UserKnownHostsFile=/dev/null -F /dev/null" \
		--exclude-from=dev/autogenerated_files.ignore \
		--exclude="/.git" \
		--exclude="/.idea" \
		. ${SANDBOX_IP}:${SANDBOX_ROOT_DIR}/

# This command will download generated files and only them from the remote sandbox to see all files locally
down: only-on-laptop
	rsync --delete -avz -e "ssh -l ${SANDBOX_USER} -i dev/GCP_KEY_FILE -p 22 -o StrictHostKeyChecking=No -o UserKnownHostsFile=/dev/null -F /dev/null" \
		--include="shop/library/Result/ResultInterface.php" \
		--exclude="/.git" \
		--exclude=".gitignore" \
		--exclude="/.idea" \
		--include-from="dev/autogenerated_files.ignore" \
		${SANDBOX_IP}:${SANDBOX_ROOT_DIR}/ .

ssh: only-on-laptop
	ssh -l ${SANDBOX_USER} -i dev/GCP_KEY_FILE ${SANDBOX_IP}

build: only-on-sandbox
	SERVER_NAME=${SANDBOX_HOSTNAME} \
    APP_SECRET=ChangeMe \
    POSTGRES_PASSWORD=ChangeMe \
    CADDY_MERCURE_JWT_SECRET=ChangeMe \
    docker compose -f docker-compose.yml -f docker-compose.prod.yml up -d

# These targets are used to make sure that a task is executed on the sandbox, not on laptop
only-on-sandbox:
	ls ${SANDBOX_ROOT_DIR} > /dev/null

# These targets are used to make sure that a task is executed on the laptop, not on sandbox
only-on-laptop: .git

.git:
	$(error This task needs .git directory)
