controllers:
    resource: ../src/Controller/
    type: annotation

kernel:
    resource: ../src/Kernel.php
    type: annotation

swagger_ui:
    path: /ui
    controller: api_platform.swagger.action.ui
