controllers:
    resource: ../src/Controller/
    type: annotation
    prefix: /api

kernel:
    resource: ../src/Kernel.php
    type: annotation
    prefix: /api

swagger_ui:
    path: /api/ui
    controller: api_platform.swagger.action.ui

#api_doc:
#    path: /api/docs
#    controller: api_platform.swagger_ui.action

authentication_token:
    path: /api/authentication_token
    methods: ['POST']
